meta_product_name: "Ugly foods"
meta_title: "We are a startup driven by sustainability, together we can save some foods, help the enviroment and our pockets! "
meta_description: "A marketplace for local shops to sell their ugly produce"
meta_image: "metapic.png" # should exist in `app/assets/images/`
twitter_account: "@ugly_foods"
